** Contact Details 

| *Name*    | Daljeet Singh                |
| *Phone*   | 9910069813                   |
| *Email*   | daljeet.singh123@gmail.com   |
| *Address* | Indirapuram, Ghaziabaad (UP) |

** Summary

Highly talented persistent and accomplished IT professional offering 10 years of experience in object-oriented design principles, Functional Programming, application development . Posses significant experience in designing and implementing software solutions, capable of improving software design and quality by applying new software methodologies. Gifted with good team player and high motivation.  
                                               
** Experience:

 Total : 10 years 

| *Company Name*               | *Start Data* | *End Data* | *Duration* |
|------------------------------+--------------+------------+------------|
| *HCL Technologies*           | July-2014    | current    | 2 years    |
| *Bqurious Software*          | May-2013     | july 2014  | 1.5 years  |
| *Skillnet Inc*               | Dec-2011     | May 2013   | 2 years    |
| *Infogain India Pvt Limited* | Jan 2011     | Nov 2011   | 11 Months  |
| *Bebo Technologies*          | Aug-2010     | Dec2010    | 4 months   |
| *Freelance*                  | May 2006     | Dec 2010   | 4 years    |

** Skills

| *Languages*               | Java,java-script, clojure, scala                        |     
| *Operating Systems*       | Red Hat Enterprise Linux / Arch linux                   |     
| *Databases*               | Oracle 11g , MongoDb                                    |     
| *Technologies*            | J2EE, Swing, json, XML,spring, hibernate                |     
| *Application Servers*     | Weblogic, Tomcat, jetty                                 |     
| *Editors/IDE*             | Emacs, Vim, Eclipse                                     |     
| *Version Control Systems* | git, mercurial                                          | 

** Education

| *Degree*  | *Board*                                    | *Year* | *Percentage* |
|-----------+--------------------------------------------+--------+--------------|
| *B.Tech.* | PTU(Punjab Technical University) Jalandhar |   2008 |         64.2 |
| *12th*    | CBSE Board                                 |   2000 |           62 |
| *10th*    | CBSE Board                                 |   1998 |           76 |

** Projects

*** PrideGlobal 
Nodejs Rest API development, with mongo DB backend.
Test driven development using Mocha.

*** HCL Practice 1.5 years
2 patents filed, both patents sent for filing in US after filing in India last year.
4d trajectory demo successfully completed single handedly using JavaScript and Google maps. 

*** Product development :
developed a web driver for native application for the android platform. Also developed a recorder for recording all user interactions with a chosen application. All user interactions are mapped to predefined keywords. These keywords are converted to executable code at run-time using the data driven approach for user interface testing. 
Developed cross platform installation utilities for signing and installing apps for testing purposes (for mac and windows)

*** Onsite UAT  
at client site at Vodafone Romania
Was deputed on-site for 2 months at Vodafone Romania for User Acceptance Testing for the Integration and customization of SIM with Oracle Inventory.

**** Responsibilities:
As a System Analyst responsibilities included supporting migration of Data, Reconciliation of records, Debugging and resolving bugs related to Integration of SIM with Oracle Inventory. 

**** Environment: 
Technologies:  Servlets, EJB, XML, SIM 13.2.1, Weblogic, Spring batch framework, quartz scheduler, Oracle ActiveMQ

*** Fedex FPOS
It is a swing based KIOSK application with skinnable and resolution independent look and feel. The major work revolves around designing of screens using rich GUI features for kiosk.

**** Responsibilities:
As a Sr. Software Engg. responsibilities include the analysis of requirements, coding, design document, designing of validation framework, designing of UI framework, R&D, Team mentoring and training.

**** Environment:
Technologies: Java, Swing , synth Look and Feel, MIG layout.

*** GWT Widgets
This work involved Building of widgets in GWT for an Enterprise Corporate Legal Software. The   widgets built had to be integrated with the provided web services and also integrated with already developed JSP pages.

**** Responsibilities:
As a Software Engineer responsibilities include the analysis of requirements, design and architecture, coding, documentation, client interaction, designing of UI framework, R&D. 

**** Environment:
Technologies: Java, GWT(Google Web toolkit), jsp, servlets, spring, hibernate


*** Ecopolis Board Game
This is a dice and board game similar to monopoly where users can sell and buy property, This game has a theme based on environment conservation and aims to teach students various benefits of using renewable energy resources.This is a multi player network game, It also supports game rooms according to location of a user.

**** Responsibilities:
As a freelancer responsibilities include bidding, the analysis of requirements, design and architecture, coding, documentation, client interaction, designing of UI framework, R&D.

**** Environment:
Technologies: Java, Swing, jna(java native Access), swinglabs, Apache Mina Server, serialization 

** Personal Details
| *Date of birth*   | 3rd June 1982                     |
| *Marital Status*  | Single                            |
| *Nationality*     | Indian                            |
| *Languages*       | English, Hindi, Punjabi           |
| *Passport Number* | H9966746 (valid upto 28-Mar-2020) |

** Hobbies 

- Takes keen interest in reading web-logs and articles related to computer science and information technology.
- He solves puzzles and riddles in his free time.
 
