# #+TITLE: Daljeet Singh
#+OPTIONS: toc:nil H:10 tex:t
#+STARTUP: hidestars indent
#+LaTeX_HEADER: \usepackage{mycv}
#+LaTeX_HEADER: \hypersetup{colorlinks=true, urlcolor={url-gray}}
#+LaTeX_CLASS_OPTIONS: [letterpaper]
#+LaTeX_HEADER: \usepackage{enumitem}
#+LaTeX_HEADER: \setlist{leftmargin=0.25in,nosep}
# #+AUTHOR: Daljeet Singh
#+EMAIL: daljeet.singh123@gmail.com
#+LANGUAGE:    ‘en’ 
** Contact Details 
#+ATTR_HTML: :frame void
#+ATTR_LATEX: :environment tabular :align rp{0.85\textwidth}
|        <r> |                              |
|    *Name:* | Daljeet Singh                |
|   *Phone:* | +91-9910069813               |
|   *Email:* | daljeets@hcl.com             |
| *Email 2:* | daljeet.singh123@gmail.com   |
|  *SAP ID:* | 51511961                     |
| *Address:* | Indirapuram, Ghaziabaad (UP) |

** Summary

Highly talented persistent and accomplished IT professional offering 10 years of experience in object-oriented design principles, Functional Programming, application development. Posses significant experience in designing and implementing software solutions, capable of improving software design and quality by applying new software methodologies. Gifted with good team player and high motivation.  

I am a Functional Programming and  LISP(Clojure) Enthusiast. 

** Skills

| *Languages*               | Java,TypeScript, Java-script, Clojure, Scala, GWT, Android |
| *Operating Systems*       | Red Hat Enterprise Linux / Arch linux                      |
| *Databases*               | Oracle 11g , MongoDb                                       |
| *Technologies*            | J2EE, Swing, spring, hibernate                             |
| *Application Servers*     | Weblogic, Tomcat, jetty                                    |
| *Editors/IDE*             | Emacs, Vim, Eclipse                                        |
| *Version Control Systems* | git, mercurial                                             |
| *Diagramming Tools*       | PlantUML                                                   |

** Experience:

Total : 10 years 

| *Company Name*               | *Start Data* | *End Data* | *Duration* |
|------------------------------+--------------+------------+------------|
| *HCL Technologies*           | July-2014    | current    | 2 years    |
| *Bqurious Software*          | May-2013     | july 2014  | 1.5 years  |
| *Skillnet Inc*               | Dec-2011     | May 2013   | 2 years    |
| *Infogain India Pvt Limited* | Jan 2011     | Nov 2011   | 11 Months  |
| *Bebo Technologies*          | Aug-2010     | Dec2010    | 4 months   |
| *Freelance*                  | May 2006     | Dec 2010   | 4 years    |

** Projects

*** PrideGlobal 
Human Resource Management System, with below  Features :
1. Requisition Management 
2. Candidate Management
3. Supplier Management 
4. Client Management

**** Responsibilities
1. Code review and quality enhancement with following considerations
   - Maintainability and preciseness of code  
   - Scalability  
2. Training the team on TDD and Functional Programming
3. Setting up test case framework
4. Evaluation and classibfication of Bugs/Enhancements 
5. Coding the core areas, and performance enhancement
6. Managing git workflow. 

**** Environment
1. MEAN stack (mongoDB, expressJS, Angular and Nodejs ). 
2. REST API development
3. With mongo DB backend
4. logging using jackson
5. jwt security
6. Test Driven Development using Mocha.


*** Pangea Analytics Platform

**** Responsibilities
1. REST APIs in Java/Spring boot
2. Deployment Diagrams using PlantUML
3. Managing a Hadoop Cluster.
4. Scala and Spark  

*** 4D Trajectory POC Aero Domain
1) 2 patents filed, both patents sent for filing in US after filing in India last year.
2) 4d trajectory demo successfully completed using JavaScript and Google maps. 
**** Environment
     TypeScript, Javascript, Google Maps API


*** Product development :
developed a web driver for native application for the android platform. Also developed a recorder for recording all user interactions with a chosen application. All user interactions are mapped to predefined keywords. These keywords are converted to executable code at run-time using the data driven approach for user interface testing. 
Developed cross platform installation utilities for signing and installing apps for testing purposes (for mac and windows)

*** Onsite UAT  
at client site at Vodafone Romania
Was deputed on-site for 2 months at Vodafone Romania for User Acceptance Testing for the Integration and customization of SIM with Oracle Inventory.

**** Responsibilities:
As a System Analyst responsibilities included supporting migration of Data, Reconciliation of records, Debugging and resolving bugs related to Integration of SIM with Oracle Inventory. 

**** Environment: 
Technologies:  Servlets, EJB, XML, SIM 13.2.1, Weblogic, Spring batch framework, quartz scheduler, Oracle ActiveMQ

*** Fedex FPOS
It is a swing based KIOSK application with skinnable and resolution independent look and feel. The major work revolves around designing of screens using rich GUI features for kiosk.

**** Responsibilities:
As a Sr. Software Engg. responsibilities include the analysis of requirements, coding, design document, designing of validation framework, designing of UI framework, R&D, Team mentoring and training.

**** Environment:
Technologies: Java, Swing , synth Look and Feel, MIG layout.

*** GWT Widgets
This work involved Building of widgets in GWT for an Enterprise Corporate Legal Software. The   widgets built had to be integrated with the provided web services and also integrated with already developed JSP pages.

**** Responsibilities:
As a Software Engineer responsibilities include the analysis of requirements, design and architecture, coding, documentation, client interaction, designing of UI framework, R&D. 

**** Environment:
Technologies: Java, GWT(Google Web toolkit), jsp, servlets, spring, hibernate

** Education

| *Degree*  | *Board*                                    | *Year* | *Percentage* |
|-----------+--------------------------------------------+--------+--------------|
| *B.Tech.* | PTU(Punjab Technical University) Jalandhar |   2008 |         64.2 |
| *12th*    | CBSE Board                                 |   2000 |           62 |
| *10th*    | CBSE Board                                 |   1998 |           76 |

** Personal Details
| *Date of birth*   | 3rd June 1982                     |
| *Nationality*     | Indian                            |
| *Languages*       | English, Hindi, Punjabi           |

** Hobbies 

1) Takes keen interest in reading web-logs and articles related to computer science and information technology.
2) lisp/clojure enthusiast
3) Linux/emacs/vim freak 
   # TODO this is a comment
